# Generated by Django 4.2.2 on 2023-06-15 23:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Planet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "chemical_elements",
                    models.CharField(max_length=200, verbose_name="Elementos químicos"),
                ),
                (
                    "percentage_of_water",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Porcentagem de água",
                    ),
                ),
                (
                    "alphaR_distance",
                    models.PositiveIntegerField(
                        verbose_name="Distância até alphaR em km"
                    ),
                ),
                (
                    "probability_of_life",
                    models.CharField(
                        choices=[
                            ("Incerta", "Incerta"),
                            ("Provável", "Provável"),
                            ("Improvável", "Improvável"),
                        ],
                        max_length=20,
                        verbose_name="Probabilidade de vida",
                    ),
                ),
            ],
        ),
    ]
